spring.application.name=innovatechRecursos
server.port=8082


# Conexión MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_recursos?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update