spring.application.name=innovatechProject
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/db_projects?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update