spring.application.name=innovatech
server.port=8080

# URLs de tus microservicios internos
url.proyectos=http://localhost:8081/api/projects/listar
url.recursos=http://localhost:8082/api/resources/listar
url.analitica=http://localhost:8083/api/analytics/listar